### PR TITLE
Added .gitignore.

### PR DESCRIPTION
**Pull request by thewarsawpakt**
.gitignore for anyone using vscode.

### CODE REVIEW

**Comment by Sophon96** [comment]
May as well toss everything in there

**Comment by Sophon96** [comment]
`.idea`, etc

**Comment by caughtquick** [comment]
Fine with me and looks good

**Comment by Sophon96** [comment]
LGTM

**Comment by Sophon96** [comment]
How do I do the thing where I approve it

**Comment by Sophon96** [comment]
Oh nvm

**Review by Sophon96 — APPROVED** [review]
LGTM

**Comment by Sophon96** [comment]
@caughtquick

**Review by caughtquick — APPROVED** [review]
Approved

**Pull request merged**
