### PR TITLE
Renamed "twirl" to "libtwirl" in imports

### PR DESCRIPTION
**Pull request by mugman174**
I just did this bc it didn't run in arch linux when I tested it... idk if it'll work so you people review it.

### CODE REVIEW

**Comment by mugman174** [comment]
### _**e**_

> [``](

- 

- [ ] @ #1. url

)

**Review by caughtquick — APPROVED** [review]
Perfect thanks

**Review by thewarsawpakt — APPROVED** [review]
I think we should replace all occurrences of "twirl" in this repo to "libtwirl" or "_twirl" to prevent naming issues.

**Comment by mugman174** [comment]
> I think we should replace all occurrences of "twirl" in this repo to "libtwirl" or "_twirl" to prevent naming issues.

yeah

**Comment by caughtquick** [comment]
> > I think we should replace all occurrences of "twirl" in this repo to "libtwirl" or "_twirl" to prevent naming issues.
> 
> 
> 
> yeah
I prefer libtwirl as that signifies what it's actually referring to rather than a "hacky" way to avoid naming issues.

**Comment by thewarsawpakt** [comment]
I wouldn't call it "hacky", moreso just a naming convention to denote internal objects.

**Comment by caughtquick** [comment]
> I wouldn't call it "hacky", moreso just a naming convention to denote internal objects.

Yeah I wouldn't either really, just libtwist makes more sense logically

**Pull request merged**
