### PR TITLE
Removed extra single line functions, fix circular imports.

### PR DESCRIPTION
**Pull request by Sophon96**

### CODE REVIEW

**Comment by Sophon96** [comment]
@BBaoVanC @thewarsawpakt @FjorgeTheHuman

**Comment by thewarsawpakt** [comment]
has this been tested?

**Comment by Sophon96** [comment]
<@115076234869735428> <@487049413626298399> <@314539203801382912>

**Comment by Sophon96** [comment]
> has this been tested?

Yessir

**Comment by Sophon96** [comment]
Oh wait embeds don't ping lmao

**Review by thewarsawpakt — APPROVED** [review]
❤️

**Comment by Sophon96** [comment]
I what
image

**Review by thewarsawpakt — APPROVED** [review]
approve 2 electric boogaloo

**Comment by BBaoVanC** [comment]
> I what
> image

It's because you pushed a commit.

**Review by caughtquick — APPROVED** [review]
LGTM, nice job

**Pull request merged**
