### PR TITLE
Added dockerfile too.

### PR DESCRIPTION
**Pull request by thewarsawpakt**

### CODE REVIEW

**Comment by caughtquick** [comment]
Did you remove the gitignore for vscode? Or split files

**Comment by thewarsawpakt** [comment]
> Did you remove the gitignore for vscode? Or split files

Not that I know of.

**Review by mugman174 — APPROVED** [review]
:+1:

**Comment by caughtquick** [comment]
Second part looks a little messy, but idrk docket too well

**Comment by caughtquick** [comment]
Looks fine, approved

**Review by caughtquick — APPROVED** [review]

**Comment by eatmyvenom** [comment]
Why is the docker file needed in the git repo?

**Comment by thewarsawpakt** [comment]
> Why is the docker file needed in the git repo?

That's a good point, however some of the development team isn't on arch, therefore testing the code on their host system isn't feasible.

**Comment by mugman174** [comment]
> > Why is the docker file needed in the git repo?
> 
> That's a good point, however some of the development team isn't on arch, therefore testing the code on their host system isn't feasible.

Like me. Also, can you add a dockerfile to my thing

**Pull request merged**
