### PR TITLE
docker start for people not on arch

### PR DESCRIPTION
**Pull request by thewarsawpakt**
more cool docker scripts

### CODE REVIEW

**Review by mugman174 — APPROVED** [review]
Cool I’d use that 👍

**Review by caughtquick — APPROVED** [review]
Looks good, approving and merging

**Comment by mugman174** [comment]
It doesn't work on Ubuntu tho...

**Comment by thewarsawpakt** [comment]
> It doesn't work on Ubuntu tho...

where does it error?

**Comment by mugman174** [comment]
[Message Link](https://discord.com/channels/808502463798968331/816455394464628737/816896889365987338)

**Comment by mugman174** [comment]
https://bugs.archlinux.org/task/69563

**Comment by thewarsawpakt** [comment]
so it's an upstream issue with ubuntu, and there's nothing I can do to fix it?

**Comment by mugman174** [comment]
Pretty much

**Comment by mugman174** [comment]
> It looks like the failure is happening when something calls faccessat2() (EDIT: when the host is running an older kernel):

faccessat2(AT_FDCWD, "/var/lib/pacman/", F_OK, AT_EACCESS) = -1 EPERM (Operation not permitted)

faccessat2() was introduced in Linux 5.8, so glibc 2.33 won't work in containers on hosts that have older kernels.

It looks like this is the commit that was responsible: https://sourceware.org/git/?p=glibc.git;a=commit;h=3d3ab573a5f3071992cbc4f57d50d1d29d55bde2

**Comment by mugman174** [comment]
YESSS I FOUND A F!X
https://bugs.archlinux.org/task/69563#comment196582

**Pull request merged**
