### PR TITLE
Read Comment

### PR DESCRIPTION
**Pull request by mugman174**
Someone make this work I added some blueprint stuff please edit this to work.

### CODE REVIEW

**Review by thewarsawpakt — APPROVED** [review]
Thanks. Looks good.

**Comment by mugman174** [comment]
Wait - edit it so it works

**Comment by mugman174** [comment]
Bc idk if it’ll work

**Comment by thewarsawpakt** [comment]
> Wait - edit it so it works

from what I read yes, it does
however I also haven't slept yet and it's super late.

**Comment by mugman174** [comment]
Ok

**Comment by mugman174** [comment]
One more person…

**Comment by BBaoVanC** [comment]
I might go and squash/rebase this so it doesn't look as crazy

**Comment by FjorgeTheHuman** [comment]
fr i told you i already had a branch for this exact thing im working on, 
stop working on a diff version of the exact same thing as others its not productive

**Comment by FjorgeTheHuman** [comment]
please no not merge this, my branch also has other changes which would make painful conflicts

**Comment by FjorgeTheHuman** [comment]
after testing my own branch for a while, its safe to say **this patch will not work**

**Comment by FjorgeTheHuman** [comment]
Same functionality implimented in #10

**Comment by mugman174** [comment]
The point was you make changes to it so it works

**Comment by FjorgeTheHuman** [comment]
That would've been better as a draft PR

**Comment by caughtquick** [comment]
he had told you he was working on this functionality and had completed it and hadn't submitted it for PR. This is incomplete compared to his so we approved his and left yours unapproved. If you feel what you have done ads functionality, speed or cleanliness modify it to fit fjorge's implementation

**Comment by mugman174** [comment]
So he did what I asked but in his own branch
Ok

**Comment by FjorgeTheHuman** [comment]
I started mine before you even make this PR so no that isn't what I did

**Pull request closed without merging**
