### PR TITLE
Use neofetch instead of bash

### PR DESCRIPTION
**Pull request by mugman174**
Arch has bash by default, but not neofetch.

### CODE REVIEW

**Comment by FjorgeTheHuman** [comment]
I'm pretty sure you're meant to be able to edit the file and enter in the program you want to test installing.

**Comment by mugman174** [comment]
This is just a nicer default anyways.

**Comment by thewarsawpakt** [comment]
You can edit the file anyways.

**Comment by caughtquick** [comment]
use the new fetch tool that we are creating that will come packaged with it

**Comment by caughtquick** [comment]
yeah I know not yet, and we are also doing out own repos so we can package it on that when the system is closer to completion.

**Comment by mugman174** [comment]
> use the new fetch tool that we are creating that will come packaged with it

but that's not on the aur and it needs to be installed using libtwirl (or pacman)

**Comment by thewarsawpakt** [comment]
However, it is not close to completion at the moment therefore changing it to a nonexistent package serves no purpose.

**Comment by caughtquick** [comment]
yeah it was more of a suggestion for the future

**Pull request closed without merging**
