### PR TITLE
cleaner errors

### PR DESCRIPTION
**Pull request by FjorgeTheHuman**
traceback bad >:(

### CODE REVIEW

**Comment by FjorgeTheHuman** [comment]
image
includes hot warnings and errors (pink because blame endeavouros devs)

**Review by caughtquick — APPROVED** [review]
This loosk good, didn't spot any errors personally

**Comment by thewarsawpakt** [comment]
I disagree with removing errors. Using errors allows us to raise and handle them, which is much neater than using a `warn` function. Python has built in support for warnings and exceptions, why not use those?

**Review by caughtquick — DISMISSED** [review]
approved again

**Review by caughtquick — APPROVED** [review]

**Comment by caughtquick** [comment]
> I disagree with removing errors. Using errors allows us to raise and handle them, which is much neater than using a `warn` function. Python has built in support for warnings and exceptions, why not use those?

i disagree, using our own implementation allows more control on logging as well as what generates what errors

**Comment by thewarsawpakt** [comment]
> using our own implementation 

My custom errors were already a custom implementation.
>  allows more control on logging

You say this as if we can't use a log or print inside of an exception.

>  as well as what generates what errors
Such as choosing to raise an exception or not?

**Comment by caughtquick** [comment]
> > using our own implementation
> 
> My custom errors were already a custom implementation.
> 
> > allows more control on logging
> 
> You say this as if we can't use a log or print inside of an exception.
> 
> > as well as what generates what errors
> > Such as choosing to raise an exception or not?

if you feels thats the best approach then we can go with it, it was just fine with me the other way though

**Comment by FjorgeTheHuman** [comment]
Trapping errors I think would in the end be way more messy than having some neat little functions. I don't even know if you can control the exit code with errors.

**Comment by FjorgeTheHuman** [comment]
plus this provides a standard way for us to log messages

**Review by mugman174 — APPROVED** [review]

**Comment by thewarsawpakt** [comment]
> Trapping errors I think would in the end be way more messy than having some neat little functions. I don't even know if you can control the exit code with errors.
Why would we need to control the exit code?

**Comment by FjorgeTheHuman** [comment]
> > Trapping errors I think would in the end be way more messy than having some neat little functions. I don't even know if you can control the exit code with errors.
> Why would we need to control the exit code?

that was just an example

**Comment by caughtquick** [comment]
> > Trapping errors I think would in the end be way more messy than having some neat little functions. I don't even know if you can control the exit code with errors.
> > Why would we need to control the exit code?

for documentation?

**Comment by thewarsawpakt** [comment]
> > > Trapping errors I think would in the end be way more messy than having some neat little functions. I don't even know if you can control the exit code with errors.
> > > Why would we need to control the exit code?
> 
> for documentation?

What sort of documentation? I would prefer an example.

**Comment by FjorgeTheHuman** [comment]
I still think this is better because like I said, it provides a standard way for us to print certain types of messages to the terminal, it's very consistent

**Comment by thewarsawpakt** [comment]
> I still think this is better because like I said, it provides a standard way for us to print certain types of messages to the terminal, it's very consistent

Where is the _built in_ support for exceptions and warnings not standard or consistent?

**Comment by Sophon96** [comment]
> I don't even know if you can control the exit code with errors.
Why wouldn't you? Just decide what exit code you're going to exit with in your handler.

I agree with pakt on this one. 
Trapping errors is pretty much the Python standard for error handling. You raise an Exception, the thing handles it and does stuff.
This makes it a lot more modular as well. Considering that this repo caries the name of **`lib`**`twirl`, its probably meant to be a library. We shouldn't hard code things, rather let the people who use it control it.

**Comment by mugman174** [comment]
>>>>>> ​
>>>>>> ​
>>>>>> ​
>>>>>> ​
>>>>>> ​
>>>>>> ​
>>>>>> ​
>>>>>> ​
>>>>>> ​
>>>>>> ​
>>>>>> ​
>>>>>> ​

**Comment by Sophon96** [comment]
> > > > > > > ​
> > > > > > > ​
> > > > > > > ​
> > > > > > > ​
> > > > > > > ​
> > > > > > > ​
> > > > > > > ​
> > > > > > > ​
> > > > > > > ​
> > > > > > > ​
> > > > > > > ​
> > > > > > > ​

tf

**Comment by FjorgeTheHuman** [comment]
> > I still think this is better because like I said, it provides a standard way for us to print certain types of messages to the terminal, it's very consistent
> 
> Where is the _built in_ support for exceptions and warnings not standard or consistent?

its consistent w/ other logging such as if we want to output debug messages

**Comment by caughtquick** [comment]
while I understand that approach @Sophon96, having our own exit codes allows similar errors to have similar numbers which honestly allow an easier approach to error codes and makes documenting simpler. Also allows logging with other errors

**Comment by FjorgeTheHuman** [comment]
> > I don't even know if you can control the exit code with errors.
> 
> Why wouldn't you? Just decide what exit code you're going to exit with in your handler.
> 
> I agree with pakt on this one.
> Trapping errors is pretty much the Python standard for error handling. You raise an Exception, the thing handles it and does stuff.
> This makes it a lot more modular as well. Considering that this repo caries the name of **`lib`**`twirl`, its probably meant to be a library. We shouldn't hard code things, rather let the people who use it control it.

I'm also against us having a frontend for a wrapper for a binding of another library, I think this repo should just be the whole pkg manager

**Comment by Sophon96** [comment]
> while I understand that approach @Sophon96, having our own exit codes allows similar errors to have similar numbers which honestly allow an easier approach to error codes and makes documenting simpler. Also allows logging with other errors

I realize. What does that have to do with what I said?

**Comment by Sophon96** [comment]
> > > I don't even know if you can control the exit code with errors.
> > 
> > 
> > Why wouldn't you? Just decide what exit code you're going to exit with in your handler.
> > I agree with pakt on this one.
> > Trapping errors is pretty much the Python standard for error handling. You raise an Exception, the thing handles it and does stuff.
> > This makes it a lot more modular as well. Considering that this repo caries the name of **`lib`**`twirl`, its probably meant to be a library. We shouldn't hard code things, rather let the people who use it control it.
> 
> I'm also against us having a frontend for a wrapper for a binding of another library, I think this repo should just be the whole pkg manager

We should rename this repo back to Twirl then.

**Comment by mugman174** [comment]
> > > I don't even know if you can control the exit code with errors.
> > 
> > 
> > Why wouldn't you? Just decide what exit code you're going to exit with in your handler.
> > I agree with pakt on this one.
> > Trapping errors is pretty much the Python standard for error handling. You raise an Exception, the thing handles it and does stuff.
> > This makes it a lot more modular as well. Considering that this repo caries the name of **`lib`**`twirl`, its probably meant to be a library. We shouldn't hard code things, rather let the people who use it control it.
> 
> I'm also against us having a frontend for a wrapper for a binding of another library, I think this repo should just be the whole pkg manager

This is a lib, not a package manager tho

**Comment by caughtquick** [comment]
I agree with fjorge here, having twrl (twrl?) being deprecated and built into libtwirl is honestly my favorite approach to this, even if it reduces extensibility

**Comment by FjorgeTheHuman** [comment]
> > > > I don't even know if you can control the exit code with errors.
> > > 
> > > 
> > > Why wouldn't you? Just decide what exit code you're going to exit with in your handler.
> > > I agree with pakt on this one.
> > > Trapping errors is pretty much the Python standard for error handling. You raise an Exception, the thing handles it and does stuff.
> > > This makes it a lot more modular as well. Considering that this repo caries the name of **`lib`**`twirl`, its probably meant to be a library. We shouldn't hard code things, rather let the people who use it control it.
> > 
> > 
> > I'm also against us having a frontend for a wrapper for a binding of another library, I think this repo should just be the whole pkg manager
> 
> We should rename this repo back to Twirl then.

we should but I don't want to do it on my own

**Comment by thewarsawpakt** [comment]
> > > I still think this is better because like I said, it provides a standard way for us to print certain types of messages to the terminal, it's very consistent
> > 
> > 
> > Where is the _built in_ support for exceptions and warnings not standard or consistent?
> 
> its consistent w/ other logging such as if we want to output debug messages

```py
class TwirlPackageAlreadyInstalled(Warning):
    def __init__(self, *args):
         print(f"Package {*args[0]} is already installed. Continuing.")
         logger.log(something)
```

**Comment by caughtquick** [comment]
leave merging twirl with libtwril to me, ill get to it in a couple of hours

**Comment by caughtquick** [comment]
that is if it a decision to make it one repo and package

**Comment by FjorgeTheHuman** [comment]
> > > > I still think this is better because like I said, it provides a standard way for us to print certain types of messages to the terminal, it's very consistent
> > > 
> > > 
> > > Where is the _built in_ support for exceptions and warnings not standard or consistent?
> > 
> > 
> > its consistent w/ other logging such as if we want to output debug messages
> 
> ```python
> class TwirlPackageAlreadyInstalled(Warning):
>     def __init__(self, *args):
>          print(f"Package {*args[0]} is already installed. Continuing.")
>          logger.log(something)
> ```

IMO the class name is so long it gets kind of messy
I don't feel like arguing rn, can we just keep this open and continue tomorrow?

**Comment by thewarsawpakt** [comment]
> > > > > I still think this is better because like I said, it provides a standard way for us to print certain types of messages to the terminal, it's very consistent
> > > > 
> > > > 
> > > > Where is the _built in_ support for exceptions and warnings not standard or consistent?
> > > 
> > > 
> > > its consistent w/ other logging such as if we want to output debug messages
> > 
> > 
> > ```python
> > class TwirlPackageAlreadyInstalled(Warning):
> >     def __init__(self, *args):
> >          print(f"Package {*args[0]} is already installed. Continuing.")
> >          logger.log(something)
> > ```
> 
> IMO the class name is so long it gets kind of messy
> I don't feel like arguing rn, can we just keep this open and continue tomorrow?

I'd be fine with that.

**Pull request closed without merging**
