### PR TITLE
Just move twrl over to libtwirl ig

### PR DESCRIPTION
**Pull request by mugman174**

### CODE REVIEW

**Comment by FjorgeTheHuman** [comment]
I prefer using our already implemented "frontend" and adapting it for CLI tbh

**Comment by mugman174** [comment]
That's pretty much what twrl is

**Comment by mugman174** [comment]
but it's easier for the end user, and prolly gonna be more customizable

**Comment by FjorgeTheHuman** [comment]
> That's pretty much what twrl is

have you even read any of its source code before you posted that comment

**Comment by FjorgeTheHuman** [comment]
> but it's easier for the end user, and prolly gonna be more customizable

thats why my plan is to *adapt* it, not to use it as is

**Comment by mugman174** [comment]
yes

**Comment by mugman174** [comment]
we'll adapt it

**Comment by mugman174** [comment]
its not complete yet

**Comment by FjorgeTheHuman** [comment]
send

**Comment by FjorgeTheHuman** [comment]
more

**Comment by FjorgeTheHuman** [comment]
than

**Comment by FjorgeTheHuman** [comment]
three words per comment

**Comment by mugman174** [comment]
ok. so, can you review it?
# h1
## h2
### h3
**bold**
*italic*
[link](https://github.com/Generic-Linux/libtwirl/pull/19)

- [ ] Checkbox

**Comment by mugman174** [comment]
oop attached a bunch of random stuff by accident - just fixed it

**Comment by FjorgeTheHuman** [comment]
i dont wanna approve it because we already got a better version already in the repository

**Comment by mugman174** [comment]
better version of what?

**Comment by FjorgeTheHuman** [comment]
> better version of what?

of twrl

**Comment by mugman174** [comment]
where

**Comment by mugman174** [comment]
also it's easier to do `./twrl` than `python3 -m libtwirl`

**Comment by BBaoVanC** [comment]
can you stop message splitting

**Comment by FjorgeTheHuman** [comment]
> also it's easier to do `./twrl` than `python3 -m libtwirl`

this whole time ive been saying we can just add a shebang and move the file and bam u can do the exact same thing

**Comment by mugman174** [comment]
ok then. so what are we gonna do with `twrl`?

**Comment by BBaoVanC** [comment]
if you keep it how it is without merging anything, then you can just run `./twrl`

**Comment by thewarsawpakt** [comment]
> this whole time ive been saying we can just add a shebang and move the file and bam u can do the exact same thing
exactly

**Comment by mugman174** [comment]
move which file

**Comment by thewarsawpakt** [comment]
> if you keep it how it is without merging anything, then you can just run `./twrl`

the issue is that twrl implements things both itself and uses libtwirl's abstractions, making it confusing.

**Comment by FjorgeTheHuman** [comment]
> move which file

the only file ive mentioned this whole time thats already in the repo?

**Comment by caughtquick** [comment]
Nothing, we will look at twrl source code and adapt it to work in libtwirl, on that not we should rename libtwirl to just twirl

**Comment by BBaoVanC** [comment]
Actually, maybe we should merge it, and keep it all in one file. But I'm not sure.

**Comment by mugman174** [comment]
> > if you keep it how it is without merging anything, then you can just run `./twrl`
> 
> the issue is that twrl implements things both itself and uses libtwirl's abstractions, making it confusing.

how about it'll mainly use libtwirl's abstractions but have some extra features

**Comment by FjorgeTheHuman** [comment]
> > if you keep it how it is without merging anything, then you can just run `./twrl`
> 
> 
> 
> the issue is that twrl implements things both itself and uses libtwirl's abstractions, making it confusing.

and we also dont need a midlayer its just confusing, heavy, and unnecessary

**Comment by mugman174** [comment]
> Nothing, we will look at twrl source code and adapt it to work in libtwirl, on that not we should rename libtwirl to just twirl

yeah that seems nice, but I think [this](https://github.com/Generic-Linux/libtwirl/pull/19#issuecomment-791118750) is better.

**Comment by caughtquick** [comment]
Why can't those "extra features" be implemented into libtwirl itself, more layers ads more complexion, even when that complexion isn't necessary

**Comment by mugman174** [comment]
> Why can't those "extra features" be implemented into libtwirl itself, more layers ads more complexion, even when that complexion isn't necessary

I never said that we couldn't integrate `twrl` into libtwirl

**Comment by FjorgeTheHuman** [comment]
> Actually, maybe we should merge it, and keep it all in one file. But I'm not sure.

`__main__.py` is imo already basically ready as a frontend except that it cant be executed directly, but thats a trivial change

**Comment by mugman174** [comment]
> > Actually, maybe we should merge it, and keep it all in one file. But I'm not sure.
> 
> `__main__.py` is imo already basically ready as a CLI tool except that it cant be executed directly, but thats a trivial change

ok let's combine `twrl` with `__main__.py` and make it work? just giving an idea here

**Comment by FjorgeTheHuman** [comment]
> > > Actually, maybe we should merge it, and keep it all in one file. But I'm not sure.
> 
> > 
> 
> > `__main__.py` is imo already basically ready as a CLI tool except that it cant be executed directly, but thats a trivial change
> 
> 
> 
> ok let's combine `twrl` with `__main__.py` and make it work? just giving an idea here

but theres no need for combining, `__main__.py` already does what `twrl` does

**Comment by mugman174** [comment]
> > > > Actually, maybe we should merge it, and keep it all in one file. But I'm not sure.
> > 
> > 
> > > 
> > 
> > 
> > > `__main__.py` is imo already basically ready as a CLI tool except that it cant be executed directly, but thats a trivial change
> > 
> > 
> > ok let's combine `twrl` with `__main__.py` and make it work? just giving an idea here
> 
> but theres no need for combining, `__main__.py` already does what `twrl` does

but `twrl` does it better

**Comment by caughtquick** [comment]
> > > Actually, maybe we should merge it, and keep it all in one file. But I'm not sure.
> 
> > 
> 
> > `__main__.py` is imo already basically ready as a CLI tool except that it cant be executed directly, but thats a trivial change
> 
> 
> 
> ok let's combine `twrl` with `__main__.py` and make it work? just giving an idea here

What purpose does that do, with a trivial change we can make libtwirl be interfaced direcrly with the command line, making it bloated to have the need to have whole bother layer for something that can be done equivalently with like I said trivial change

**Comment by mugman174** [comment]
> > > > Actually, maybe we should merge it, and keep it all in one file. But I'm not sure.
> > 
> > 
> > > 
> > 
> > 
> > > `__main__.py` is imo already basically ready as a CLI tool except that it cant be executed directly, but thats a trivial change
> > 
> > 
> > ok let's combine `twrl` with `__main__.py` and make it work? just giving an idea here
> 
> What purpose does that do, with a trivial change we can make libtwirl be interfaced direcrly with the command line, making it bloated to have the need to have whole bother layer for something that can be done equivalently with like I said trivial change

lets add `twrl`'s features to `libtwirl`'s `__main__.py` so we can get rid of the twrl standalone

**Comment by FjorgeTheHuman** [comment]
> > > > > Actually, maybe we should merge it, and keep it all in one file. But I'm not sure.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > `__main__.py` is imo already basically ready as a CLI tool except that it cant be executed directly, but thats a trivial change
> 
> > > 
> 
> > > 
> 
> > > ok let's combine `twrl` with `__main__.py` and make it work? just giving an idea here
> 
> > 
> 
> > but theres no need for combining, `__main__.py` already does what `twrl` does
> 
> 
> 
> but `twrl` does it better

it really doesnt, they both do the same thing but `twrl` is significantly more complex for no reason

**Comment by mugman174** [comment]
> > > > > > Actually, maybe we should merge it, and keep it all in one file. But I'm not sure.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > `__main__.py` is imo already basically ready as a CLI tool except that it cant be executed directly, but thats a trivial change
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > ok let's combine `twrl` with `__main__.py` and make it work? just giving an idea here
> > 
> > 
> > > 
> > 
> > 
> > > but theres no need for combining, `__main__.py` already does what `twrl` does
> > 
> > 
> > but `twrl` does it better
> 
> it really doesnt, they both do the same thing but `twrl` is significantly more complex for no reason

not by much tho but ok

**Comment by mugman174** [comment]
> > > > > > Actually, maybe we should merge it, and keep it all in one file. But I'm not sure.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > `__main__.py` is imo already basically ready as a CLI tool except that it cant be executed directly, but thats a trivial change
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > ok let's combine `twrl` with `__main__.py` and make it work? just giving an idea here
> > 
> > 
> > > 
> > 
> > 
> > > but theres no need for combining, `__main__.py` already does what `twrl` does
> > 
> > 
> > but `twrl` does it better
> 
> it really doesnt, they both do the same thing but `twrl` is significantly more complex for no reason

not really but ok. its in just one file...

**Comment by caughtquick** [comment]
> > > > > Actually, maybe we should merge it, and keep it all in one file. But I'm not sure.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > `__main__.py` is imo already basically ready as a CLI tool except that it cant be executed directly, but thats a trivial change
> 
> > > 
> 
> > > 
> 
> > > ok let's combine `twrl` with `__main__.py` and make it work? just giving an idea here
> 
> > 
> 
> > but theres no need for combining, `__main__.py` already does what `twrl` does
> 
> 
> 
> but `twrl` does it better
We clean up libtwirl to interface with the command line better, all twrl does is provide a layer of abstraction that can't just be easily implemented into__main__.py

**Comment by thewarsawpakt** [comment]
At this point, nobody is actually discussing, it's just baseless "no that's wrong", "no it's not".

**Comment by mugman174** [comment]
> At this point, nobody is actually discussing, it's just baseless "no that's wrong", "no it's not".

yeah

**Comment by FjorgeTheHuman** [comment]
> > > > > Actually, maybe we should merge it, and keep it all in one file. But I'm not sure.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > `__main__.py` is imo already basically ready as a CLI tool except that it cant be executed directly, but thats a trivial change
> 
> > > 
> 
> > > 
> 
> > > ok let's combine `twrl` with `__main__.py` and make it work? just giving an idea here
> 
> > 
> 
> > What purpose does that do, with a trivial change we can make libtwirl be interfaced direcrly with the command line, making it bloated to have the need to have whole bother layer for something that can be done equivalently with like I said trivial change
> 
> 
> 
> lets add `twrl`'s features to `libtwirl`'s `__main__.py` so we can get rid of the twrl standalone

heres the thing, `twrl` has no features `__main__.py` doesnt already have

**Comment by mugman174** [comment]
how about we just merge it and do this discussion on a seperate Github discussion?

**Comment by FjorgeTheHuman** [comment]
how about we discuss it first and then merge it

**Comment by mugman174** [comment]
> how about we discuss it first and then merge it

merging won't break anything.

**Comment by caughtquick** [comment]
Are you missing the whole discussion about removing twrl from existence, merging it provides no sizable advantages

**Comment by caughtquick** [comment]
Also github discussion please, rather than this

**Comment by mugman174** [comment]
yes lets just merge this and move to a gh discussion for further stuff

**Comment by FjorgeTheHuman** [comment]
> > how about we discuss it first and then merge it
> 
> 
> 
> merging won't break anything.

itll put an extra commit we might need to revert, not merging also wont affect anything, its not like we're closing the pr right now

**Comment by mugman174** [comment]
https://github.com/orgs/Generic-Linux/teams/team-generic/discussions/4

**Comment by mugman174** [comment]
> > > how about we discuss it first and then merge it
> > 
> > 
> > merging won't break anything.
> 
> itll put an extra commit we might need to revert, not merging also wont affect anything, its not like we're closing the pr right now

we won't need to revert it tho

**Comment by thewarsawpakt** [comment]
> > how about we discuss it first and then merge it
> 
> merging won't break anything.
This is correct. I say we can merge it, start discussing elsewhere, then change it later.

**Review by thewarsawpakt — APPROVED** [review]

**Comment by caughtquick** [comment]
Yeah, no point in merging until a decision is made

**Comment by mugman174** [comment]
I made a discussion at https://github.com/orgs/Generic-Linux/teams/team-generic/discussions/4

**Comment by FjorgeTheHuman** [comment]
> > > how about we discuss it first and then merge it
> 
> > 
> 
> > merging won't break anything.
> 
> This is correct. I say we can merge it, start discussing elsewhere, then change it later.
> 
> 

i still believe we should discuss it before merging, most of this discussion was on wether `twrl` should even exist in the first place, so merging would defeat most of the point

**Comment by mugman174** [comment]
> > > > how about we discuss it first and then merge it
> > 
> > 
> > > 
> > 
> > 
> > > merging won't break anything.
> > 
> > 
> > This is correct. I say we can merge it, start discussing elsewhere, then change it later.
> 
> i still believe we should discuss it before merging, most of this discussion was on wether `twrl` should even exist in the first place, so merging would defeat most of the point

That's why [this discussion](https://github.com/orgs/Generic-Linux/teams/team-generic/discussions/4) exists.

**Comment by FjorgeTheHuman** [comment]
> > > > > how about we discuss it first and then merge it
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > merging won't break anything.
> 
> > > 
> 
> > > 
> 
> > > This is correct. I say we can merge it, start discussing elsewhere, then change it later.
> 
> > 
> 
> > i still believe we should discuss it before merging, most of this discussion was on wether `twrl` should even exist in the first place, so merging would defeat most of the point
> 
> 
> 
> That's why [this discussion](https://github.com/orgs/Generic-Linux/teams/team-generic/discussions/4) exists.

how many times are you going to post the same link? also i cant participate in discussion due to being on mobile

**Comment by mugman174** [comment]
Use the GitHub website to do discussions then

**Comment by caughtquick** [comment]
Do not merge, closing PR unless objections

**Comment by mugman174** [comment]
Ok imma just delete twrl then unless objections

**Comment by caughtquick** [comment]
don't delete twrl, we want it as a reference point, but not getting merged in.

**Pull request closed without merging**
